[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

lib_deps =
  majicdesigns/MD_MAX72XX@^3.5.1
  majicdesigns/MD_Parola@^3.7.5
  adafruit/Adafruit NeoPixel@^1.12.3

build_flags =
  -D MAX_DEVICES=4
  -D MAX7219_CLK_PIN=12
  -D MAX7219_CS_PIN=10
  -D MAX7219_DIN_PIN=11
  -D ONBOARD_RGB_PIN=48
